### ISSUE TITLE
Add buttons to save data as csv, xls, etc

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/hetmech-frontend#12]
Creating this issue for myself to add buttons to download data later. `.csv` would be easy. `.xls` might be involved but would be nice. Will discuss with @dhimmel what data we want to have available for handy/convenient download.

**Comment by vincerubinetti** [comment]
https://github.com/SheetJS/js-xlsx
https://github.com/clarketm/TableExport

**Comment by dhimmel** [comment]
Not a bad feature to have, especially for our paths tables, which could be hundreds of rows. There are likely other tables users will want (e.g. a table for all metapaths from a specific source Compound to any target Disease). We can still provide these later via an alternative interface, so a direct download link for HTML tables is not mutually exclusive.

**Comment by vincerubinetti** [comment]
Implemented in dev branch. Will be incorporated by future PR.

**Comment by vincerubinetti** [comment]
Closed by #41 and other PR that added metapath table csv download.
