### ISSUE TITLE
Invalid SVGs downloaded from graph when URL contains special characters

### ISSUE THREAD

**Issue by dhimmel** [greenelab/hetmech-frontend#142]
Here is an example SVG with invalid source:

[data.svg.txt](https://github.com/greenelab/hetmech-frontend/files/3556855/data.svg.txt)

The first four lines of this file are:

```svg
<svg xmlns="http://www.w3.org/2000/svg" id="graph" width="1800" height="940" style="left: -580px;"><title>Aripiprazole → NGLY1</title><desc>Graph visualization of the connectivity between Aripiprazole (Compound) and NGLY1 (Gene).

Created at https://het.io/search/?source=4381&target=46239&metapaths=CbGdDdG%2CCbGpBPpG%2CCbGr%3EGr%3EG%2CCdGiGr%3EG%2CCdGpBPpG%2CCdGr%3EGiG%2CCpDaGiG%2CCpDlAuG%2CCpDuGiG%2CCuG%3CrGiG&complete=
```

It seems that the special characters in the URL is causing the problem. Would we be able to put our attribution info in a comment to fix this?

**Comment by dhimmel** [comment]
An unrelated issue is that when we download a CSV it is named like `paths_Aripiprazole_NGLY1.csv`. It would be great if we could also give a descriptive name to the graph like `graph_Aripiprazole_NGLY1.csv`

**Comment by vincerubinetti** [comment]
HTML comments cannot be added with React without really dirty hacks (I know, it's a giant flaw).

To download the svg, the app has to get the full raw contents of the svg element in the document, as html/xml. But unfortunately, it seems like any possible way of getting it from the browser necessarily html-escapes the content, like `&` -> `&amp;`. 

Still looking into whether this is possible.

**Comment by dhimmel** [comment]
If you can add an arbitrary string to the SVG can't you just add an arbitrary string surrounded by the HTML comment characters? Or would the comment characters get escaped?

**Comment by vincerubinetti** [comment]
> Or would the comment characters get escaped?

Yes

**Comment by dhimmel** [comment]
What about writing the SVG to the file and then adding an html comment at the end (or before). So basically two separate writes have occurred to the same file?

**Comment by vincerubinetti** [comment]
That might work, though it's definitely not an idiomatic solution. That info really belongs in `<desc>`, and also I'm not sure that adding an html comment after or before the `<svg>` opening/closing tags is valid svg syntax. In fact I don't think it is because I think svg is a variant of xml, and thus wouldn't support html comments. It would probably work anyway in most modern browsers though.

No matter what, the code becomes very dirty and hacky.

I might just use this:
https://www.npmjs.com/package/unescape

**Comment by vincerubinetti** [comment]
Closed by https://github.com/greenelab/hetmech-frontend/pull/143

Fixed both issues with the `unescape` package.
