### ISSUE TITLE
tooltips for filters?

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/hetmech-frontend#16]
Might be nice to have tooltip text for the metatype filters. Maybe they're too basic (eg Gene) to warrant tooltips, but we have them for everything else.

Edit: and source/target node

**Comment by vincerubinetti** [comment]
Done. Will include in upcoming PR of small changes/additions.

**Comment by dhimmel** [comment]
We haven't made concise definitions for metanodes / metaedges yet. I agree they will be useful, although perhaps a bit challenging. We should look at what is available in the [Rephetio Manuscript Methods](https://git.dhimmel.com/rephetio-manuscript/#nodes) and go from there.

**Comment by vincerubinetti** [comment]
I understand the difficulty. We also don't have to get it perfect right away. They can be changed easily in the future, of course. For now, I think if we get a general "rough feeling" definition for them, just so the user has some explanation, that would be fine. The rest of the tooltips are just an introductory explanation, and would require further reading for true understanding anyway.

**Comment by dhimmel** [comment]
Well I think a "rough feeling" if inaccurate could be worse than nothing. But since I think we should have definitions for these terms, I'm happy to take the time with you now to create a pretty good set of definitions.

**Comment by dhimmel** [comment]
On further thought, let's make a `definitions.json` file in the [hetionet](https://github.com/hetio/hetionet) repo.

**Comment by dhimmel** [comment]
Looks like this was fixed in https://github.com/greenelab/hetmech-frontend/commit/2c23a4d4f0bb4ad78c8f5d3d0a528fe65e358c9c?
