### ISSUE TITLE
Integrate into https://het.io/

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/hetmech-frontend#19]
~@dhimmel There's probably other text we want to include on the page, like a copyright/license link, a link to the main [het.io](https://het.io) page, and more.~

Action item to integrate this hetmech "app" into the het.io main site. This will include several sub-actions:

- provide license info for the app and data
- provide header text (the name of the "app" or page, ie "hetio search" or "hetmech")
- possibly remove logo and transfer logo to het.io itself (on all pages)
- provide helper introductory text like the other pages on het.io, explaining the purpose of the page and providing links to more information
- redesign het.io to look better and the be consistent with the hetmech aesthetic - this action will be tracked in another repo or by some other means

**Comment by dhimmel** [comment]
Agreed. The licensing situation is difficult: our original data is released under CC0. However, the nodes and edges we show may inherit upstream licensing constraints.

Let's also discuss whether we should change https://het.io/ at all to link to this project.

**Comment by vincerubinetti** [comment]
It seems like integrating this app right into the het.io site is the most appropriate thing to do. As such, changing this issue to be that action.

**Comment by vincerubinetti** [comment]
closed by #87 !
