### ISSUE TITLE
Add path highlighting in graph view

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/hetmech-frontend#30]
Add some sort of glow or highlight for a particular path (or multiple paths?) in the graph view.

Probably will need another column of checkboxes in the paths table to allow user to show the path highlight. We could do it via mouse hover but 1) that wont work on mobile and 2) it might be hard sometimes for the user to see both the full paths table and the full graph container on screen at once.

**Comment by dhimmel** [comment]
I think it makes sense to have a way to toggle highlighting on or off for a path. However, it may also be nice to have highlight-on-hover enabled, such that the link between the path table and graph visualization is immediately clear.

**Comment by vincerubinetti** [comment]
Implemented in dev branch. Will be incorporated by future PR.

**Comment by vincerubinetti** [comment]
closed by #44 and #41

**Comment by vincerubinetti** [comment]
> such that the link between the path table and graph visualization is immediately clear.

I think there's probably a better way to accomplish this. Not sure what it is yet though. Maybe a better page layout, or helper/explanation text at the top describing the "workflow" of hetmech (when we integrate it into het.io).
