### ISSUE TITLE
Add node/edge information on click in graph visualization

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/hetmech-frontend#31]
When the user clicks or hovers a node or edge in the graph, information about that node/edge should appear somewhere. Maybe below the graph container itself, or perhaps inside the graph container in a corner. Perhaps the user could benefit from having it displayed in the corner of the graph: they could arrange the graph the way they like, select/highlight and draw attention to a specific node, show its properties, and then save it all as an svg all in the same image.

**Comment by dhimmel** [comment]
We can also consider whether it makes sense to show the definitions for the metanode/metaedge from [here](https://github.com/hetio/hetionet/commit/84aa810d4af88befc0d96d49e325a5c1a77f5995). This could be as a tooltip or however, but it may help users understand the meaning of an edge/node.

**Comment by vincerubinetti** [comment]
@dhimmel looking for input on what information would be useful to display within the boundaries of the graph (such that exporting it to .svg would contain it). All the same properties we show in the source/target node tables for the selected node? More information on the highlighted paths? How many nodes/edges? Connectivity?

**Comment by dhimmel** [comment]
> what information would be useful to display within the boundaries of the graph

Possibly the search.het.io URL with parameters... like "recreate at URL"?

I don't think we need to add too much more information that is elsewhere on the page. Although I am open to ideas.

I do not think it is important to be able to export an SVG with node / edge properties shown, but possibly it could be useful.

**Comment by vincerubinetti** [comment]
> Possibly the search.het.io URL with parameters... like "recreate at URL"?

Will do, in #33.

> I don't think we need to add too much more information that is elsewhere on the page. Although I am open to ideas.

This would be useful for nodes other than the source/target node. Let's say someone wanted to know more about a node that's in the middle of a path. Currently, they'd have to search for that node in the source/target search boxes, find the result, and then look in the info table populated below.

Perhaps in addition to, or maybe even instead of, the source/target node information tables, we could have a more horizontal table * that shows the information for not only the source/target node, but all the nodes displayed on the graph.

* "horizontal" table is like the metapath and path tables are now, "vertical" table is like how the source/node tables are now, with the field names going vertically.

**Comment by dhimmel** [comment]
> This would be useful for nodes other than the source/target node. Let's say someone wanted to know more about a node that's in the middle of a path. Currently, they'd have to search for that node in the source/target search boxes, find the result, and then look in the info table populated below.

I agree we need a way to show node and edge properties for the graph. I was envisioning that we would enable either a tooltip on node/edge hover or an information pane like Neo4j has. I don't see many users wanting to see data for all visualized nodes at once... rather than selecting nodes of interest and seeing just that metadata.
