### ISSUE TITLE
Add url parameters for saving/permalinking metapath and path selections

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/hetmech-frontend#33]
This will probably require the integration of routing.

Having the graph information (node positions and layout) in the url would probably make the url too long and probably isn't all that useful to the user, especially since if they want to share a custom layout, they can just save it as an svg and share it that way.

**Comment by dhimmel** [comment]
> Having the graph information (node positions and layout)

Agreed. Persisting which paths are selected should be enough.

**Comment by dhimmel** [comment]
# Node pair with most metapaths

I'm working on a query to find the node pair with the most metapaths:

```sql
SELECT count(id), source_id, target_id
FROM dj_hetmech_app_pathcount
GROUP BY source_id, target_id
ORDER BY count DESC
LIMIT 5;
```

**Comment by vincerubinetti** [comment]
Let's add disable or warning to metapaths with path count over certain amount.

**Comment by dhimmel** [comment]
> Let's add disable or warning to metapaths with path count over certain amount.

Path count greater than 10,000 seems like a reasonable threshold. We can reduce further if it's still a problem.

**Comment by vincerubinetti** [comment]
Metapath linking accomplished #60

**Comment by vincerubinetti** [comment]
The string needed to save path information will be too long to store in the url, unless we want to have an arbitrary cutoff point which is significantly shorter than what will be displayed in the table. I don't recommend an arbitrary cutoff as it might be confusing and unexpected to the user. 

I could try some fancy compression techniques to store more paths in the url, but I think even with that the limit will still be fairly small. In this case, I'd recommend an all or nothing approach, and since we can't do all, I recommend we do none.

As such, closing this. We can revisit path linking in the future.

**Comment by vincerubinetti** [comment]
Addendum:

Now that we're allowing all metapaths to be shown -- not just the ones above a threshold -- the url can get super long with all of the checked metapaths. So there's definitely not room for path data in there now.
