### ISSUE TITLE
Always select first n metapaths and first n paths

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/hetmech-frontend#34]
If/when we implement #33, this will probably be less necessary. Currently when testing, every time I make a change and refresh the page, I have to go through and re-select some metapaths and paths to test. It would be nice if it automatically did that for me.

But if the selected metapaths/paths were stored in the url, refreshing would maintain whatever I had selected the first time, making this irrelevant probably.

**Comment by dhimmel** [comment]
I think defaulting to selecting the top 10 paths is a good idea. As far as metapaths go, it'd be ideal to default to selecting all (if performance is not an issue).

**Comment by vincerubinetti** [comment]
Changing this to an enhancement. If/when we do #66, this will become much less necessary I think. Also, it might get a bit unnecessarily complex if we start having to conditionally checking the top 10 based on [this](https://github.com/greenelab/hetmech-frontend/issues/33#issuecomment-490615285)

**Comment by vincerubinetti** [comment]
Closing this in favor of https://github.com/greenelab/hetmech-frontend/issues/66

I don't think this is a good idea, especially give the potential serve load. And it isn't necessarily good UI design. https://github.com/greenelab/hetmech-frontend/issues/66 will make it very easy to select things quickly on desktop and mobile.
