### ISSUE TITLE
Improve graph expand/collapse

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/hetmech-frontend#67]
I notice that users have problems with the expand/collapse buttons. The "problem" is that the width of the graph expands to fit the boundaries of the screen, and then the height is set proportionally to the width in `4:3`, as to create a nice image size for exporting to `.svg`.

Perhaps instead, the graph should start as `4:3`, but then clicking the expand/collapse buttons only fits the width, and leaves the height alone. cc @dhimmel

**Comment by dhimmel** [comment]
> Perhaps instead, the graph should start as 4:3, but then clicking the expand/collapse buttons only fits the width, and leaves the height alone

That sounds reasonable. Not sure though, since it's nice to be able to click expand and have a whole subgraph be able to fit. I don't have a strong preference / will have to play around more.

**Comment by vincerubinetti** [comment]
As part of this issue, I should also change the highlight color in response to people's feedback. It's hard to find a color that doesn't conflict with any of the metanode colors and also looks good and has enough contrast. Maybe `#ffcc00`.

**Comment by dhimmel** [comment]
I like `#ffcc00` and tend to associate yellows with highlighters (even if it is similar to the Side Effect color).
