### ISSUE TITLE
Default text in search box

### ISSUE THREAD

**Issue by dongbohu** [greenelab/hetmech-frontend#83]
Since the node search API only searches `identifier` and `name` fields in a `Node` now, the default text in search box probably should be `identifier or name` instead of `id, name, or metanode`:
![Screenshot from 2019-06-13 13-37-25](https://user-images.githubusercontent.com/15133253/59454760-cb07fd80-8de0-11e9-9c81-c9e870f660b9.png)

**Comment by vincerubinetti** [comment]
Closed by https://github.com/greenelab/hetmech-frontend/pull/92
